services:
  - type: web
    name: senorita-bot
    env: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_WHISPER_MODEL
        value: whisper-large-v3-turbo
      - key: TTS_VOICE
        value: en-IN-NeerjaNeural
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YTDLP_COOKIES_B64
        sync: false
      - key: PORT
        value: 10000
